### ISSUE TITLE
Feature Request : Add exceptions

### ISSUE THREAD

**Issue by The-Steel-Talon** [eric-bixby/auto-sort-bookmarks-webext#101]
Heya,
This is a very useful extension.
But it would be great if there were some way to add exceptions.
So that in the exception list,
one would be able to add some names which would not be rearranged.
I ask this because I tend to customize the bookmarks toolbar.
What I want is a way such that,
any bookmarks that are in the toolbar, and not inside any folder in the toolbar,
would not be rearranged.
:)

**Comment by eric-bixby** [comment]
There's already a way to do that called "Configure Folders".  By default, all folders are included.  If you uncheck the checkbox next to "Bookmarks Toolbar", then the entries in that folder are excluded from sorting.  If you check the "recursive" checkbox, then entries in sub-folders are also excluded from sorting.  Since you want to sort the entries in sub-folders, leave the checkbox unchecked and they will be sorting.

**Comment by eric-bixby** [comment]
By the way, you get to that option by clicking on the "Auto-Sort Bookmarks" icon in the toolbar.

**Comment by The-Steel-Talon** [comment]
Thanks :)
