### ISSUE TITLE
Please add Pale Moon compatibility via PMkit 

### ISSUE THREAD

**Issue by LimboSlam** [eric-bixby/auto-sort-bookmarks-webext#42]
Hi there, @antoyo. First off, thanks for your wonderful and powerful add-on. It has relieved many headaches of rearranging and renaming bookmarks. This is definitely an accessibility feature, I hope it can be restored for us [Pale Moon](https://www.palemoon.org/) users. 

In fact, it's been pretty useful at what it does, I had to modify the xpi (adding our own GUID and a lower minimal install/version number) so I could install the latest and compatible version available. Although, that isn't the case anymore since [v27.1 of Pale Moon](https://www.palemoon.org/releasenotes.shtml). PMkit, is an alternative library that provides a basic compatibility layer with the Mozilla's Add-on SDK. Many add-ons have already been [successfully adapted](https://github.com/JustOff/pm27-sdk-addons/blob/master/README.md#sdk-based-add-ons-can-be-run-in-pale-moon-271-but-they-should-be-properly-adapted) and work fine in Pale Moon. Thus, it's progressing greatly as another option for our add-on developers. 

Additionally, if you could fully and officially support us please, that would be awesome. You can do this by adding our GUID/application block to the install.rdf, fixing any bugs that pertain to us, and hosting it on [APMO](https://addons.palemoon.org/) or AMO. But, that is only one of the options to support us. We offer [several other alternatives](https://developer.palemoon.org/Add-ons:Site).

Not to mention, Pale Moon uses it's own layout and rendering engine called [Goanna](https://www.moonchildproductions.info/goanna.shtml). This was put in place because "Pale Moon is not Firefox, and never will be again." Hence, the [UI differences](https://www.palemoon.org/layout-differences.shtml) and the [in-progress/future Road Map](https://www.palemoon.org/roadmap.shtml).

**-PS:** I'm not an add-on developer or in charge of this process, just a Pale Moon enthusiast. You would need to get in contact with Andrew Gilbertson (AndyTheAbsurd) or Lootyhoof (Ryan659), at our [forums](https://forum.palemoon.org/).

**Comment by antoyo** [comment]
There is a [Palemoon branch](https://github.com/antoyo/auto-sort-bookmarks/tree/palemoon) in this repository and I once tried to add it to the Palemoon add-ons website but I did not get any answer in the forum.
In any case, I am not the maintener of this add-on anymore.
@eric-bixby If you are interested, could you please take a look at it.
Thanks.

**Comment by eric-bixby** [comment]
Yes, I'll look into it.

**Comment by LimboSlam** [comment]
I'm sorry @antoyo, hopefully our team will get it right this time. Maybe @JustOff can help move the process along or answer some questions, as he is the one who made this format possible. And @eric-bixby, the thought is much appreciated.

**Comment by eric-bixby** [comment]
@LimboSlam, It's done and will be available in release 2.10.12:
https://github.com/antoyo/auto-sort-bookmarks/releases/tag/v2.10.12

**Comment by LimboSlam** [comment]
Thanks @eric-bixby! It's much appreciated. :+1: 

I have posted the good news on our forums, so maybe aspect a rise in consumer use and bug reports. :)

**Comment by Lootyhoof** [comment]
If you require this to be added to the Pale Moon Add-ons Site, let me know and I'll get it added ASAP. On AMO this add-on cannot update for Pale Moon users as PM reports as Firefox 27.9 to AMO.

**Comment by eric-bixby** [comment]
Yes, I noticed after updating to PM 27.1.1, it is reporting itself as 27.9 (using the user-agent).  In the "package.json" file, I specified version >= 27.1.0b1, which should work because 27.9 is greater than 27.1.  Seems unlikely, but maybe the UUID changed.

However, the user is able to manually able to install the file.

**Comment by Lootyhoof** [comment]
Unfortunately, due to the way that AMO deals with updates, it only looks at the Firefox version strings (which for this is, rightfully, `38.0a1`). In this sense it will state that the add-on is incompatible, however as you have found, users can still manually install from AMO (if they are aware it is compatible). However, as this same system is used when probing AMO for updates, it means that any updates will be seen as for Firefox 38.0a1 and above, which Pale Moon does not report as. This means that Pale Moon users cannot receive updates served over AMO (though they could manually install each update if they wish).

If this is not a concern for you, then feel free to carry on as you were, however if you would like Pale Moon users to receive further updates automatically there are two options open currently:

1. Host on the Pale Moon Add-ons Site: https://addons.palemoon.org/. This brings exposure to Pale Moon users who are kept safe in the knowledge that the add-on will remain compatible so long as it is listed on the site. We provide our own automatic update system in this instance, such that all that needs to be done by the developer is upload the new XPI (could be the same as the AMO version) and change some metadata on the server side.

2. Host elsewhere (e.g. GitHub), and provide an `update.rdf` file somewhere so that users can still keep updated. This way you have full control over the update infrastructure. If you wish we can still list this type of add-on on the Pale Moon Add-ons Site, but link to the external hosting rather than provide a traditional add-on listing (i.e. AMO-style).

If either of these are of interest to you, let me know and I can get things arranged for you.

**Comment by eric-bixby** [comment]
@Lootyhoof, Option 1 sounds good, if you can help make that happen, that would be appreciated.

**Comment by Lootyhoof** [comment]
Thanks, I've sent a message to the email address used in your git commits with some details. 

For those curious, this is now live:
https://addons.palemoon.org/extensions/auto-sort-bookmarks/

**Comment by eric-bixby** [comment]
I've created a new repo for Pale Moon support:
https://github.com/eric-bixby/auto-sort-bookmarks-pm
