### ISSUE TITLE
Need to disable in order to change bookmarks

### ISSUE THREAD

**Issue by browser923538** [eric-bixby/auto-sort-bookmarks-webext#92]
I can't edit my bookmarks anymore unless I disable Auto-Sort first...64-bit version of Firefox 67.0 on Windows 10 Home.

**Comment by eric-bixby** [comment]
I need more details in order to debug.
First, there are different ways to edit bookmarks, so can you list the steps you use.
Second, when you say "I can't edit", does that mean the menu is disabled, the changes are ignored, etc.  Please elaborate.
Also, did you try disabling other add-ons to isolate the problem?  Are you using a sync tool like Firefox Sync, EverSync, etc.?

**Comment by browser923538** [comment]
I can't delete bookmarks when Auto-Sort is disabled (it was the first add-on I tried to disabling to see if it had an affect and it was the culprit). (It's like the delete and backspace buttons don't even work.) I'm not using any syncing services as far as I know.

**Comment by browser923538** [comment]
Whoops I think I "closed" the issue accidentally? Also when Auto-Sort is enabled I can't add a bookmark by clicking on the star to the right of the menu but I *can* add one by hitting Ctrl-D.

**Comment by eric-bixby** [comment]
By default, the delete and backspace keys (you said buttons, but I assume you meant keys because a button means something different to me) have different uses and are not always available in Firefox.  Firefox uses backspace to go back a page, so the key you should be using is the delete key.  However, if you are using the sidebar to edit bookmarks, the delete key is not available.  The delete key is only valid for deleting bookmarks in the bookmarks manager (Show All Bookmarks) window after selecting a bookmark.

Have you tried right-clicking on the bookmark and selecting delete?

**Comment by eric-bixby** [comment]
Also, what happens when you click on the star?

**Comment by browser923538** [comment]
Right-clicking and selecting delete, nothing happens.

Also when I click on the star (nothing, it just doesn't fill in.)

**Comment by eric-bixby** [comment]
Have you tried updating your browser to the current latest version of 67.0.4?

**Comment by browser923538** [comment]
Yes I did that when it came out

**Comment by eric-bixby** [comment]
First, I forgot to mention, I'm not seeing this.

Second, do you have a lot of bookmarks, like multiple thousands?  If so, try changing the timeout before sorting.  Maybe it's trying to sort when you are adding/deleting bookmarks.

Next, try creating and switching to a new Firefox profile.  Only add this add-on to the new profile and enable auto-sorting with the default bookmarks.  Does this work correctly?  If so, then try importing your bookmarks, and check if it's still working.

**Comment by eric-bixby** [comment]
Sorry, need to close this because I cannot reproduce it.  I'm not doubting you are having a problem, but If I cannot reproduce it, then I cannot fix it.
